#!/usr/bin/fish

g++ \
  -I. \
  -Iusr/include/sysc/communication \
  -Iusr/include/sysc/datatypes/bit \
  -Iusr/include/sysc/datatypes/int \
  -Iusr/include/sysc/datatypes/misc \
  -Iusr/include/sysc/kernel \
  -Iusr/include/sysc/tracing \
  -Iusr/include/sysc/utils \
  -L. \
  -L /usr/lib \
  -Wl,-rpath=/usr/lib \
  -lsystemc -lm \
  mem.cpp extend.cpp decode.cpp reg.cpp regfile.cpp alu.cpp imem.cpp dmem.cpp shiftl2.cpp proc.cpp