#!/usr/bin/fish

# Utiltiy script to include the SystemC libraries and header files 
# during the compilation process.

g++ \
  # Including SystemC .h files
  -I. \
  -Iusr/include/sysc/communication \
  -Iusr/include/sysc/datatypes/bit \
  -Iusr/include/sysc/datatypes/int \
  -Iusr/include/sysc/datatypes/misc \
  -Iusr/include/sysc/kernel \
  -Iusr/include/sysc/tracing \
  -Iusr/include/sysc/utils \
  # Including SystemC library files for linking
  -L. \
  -L /usr/lib \
  -Wl,-rpath=/usr/lib \
  -lsystemc -lm \
  # Rest of compilation parameters... 
  $argv